# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'budget' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for budget
  # pod 'SwiftyJSON', git: 'https://github.com/SwiftyJSON/SwiftyJSON.git'
  # pod 'Charts', git: 'https://github.com/danielgindi/Charts.git'
  pod 'SwiftyJSON', '4.0.0'
  pod 'Charts', '3.0.3'

  target 'budgetTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'budget-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for budget-tvOS

  target 'budget-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0'
    end
  end
end
